name: Build, Test and Analyze

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - name: Setup
        run: make setup
      - name: Analyze
        run: flutter analyze

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - name: Setup
        run: make setup
      - name: Unit Tests
        run: flutter test test/unit

  widget-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - name: Setup
        run: make setup
      - name: Widget Tests
        run: flutter test test/widget

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - name: Setup
        run: make setup
      - name: Build release package
        run: flutter build apk --release --target-platform=android-arm
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk